# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification on push
        uses: appleboy/telegram-action@master
        with:
          to: -4567376206
          token: 7515836304:AAHrfYhgCuFFKcyyvYvrdy8wf3lF6CWrT28
          message: ${{ github.event.head_commit.message }}
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - run: pnpm i
      - run: npx nuxt build --preset github_pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Send Telegram notification on push
        uses: appleboy/telegram-action@master
        with:
          to: -4567376206
          token: 7515836304:AAHrfYhgCuFFKcyyvYvrdy8wf3lF6CWrT28
          message: ${{ github.event.head_commit.message }}
